### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by le-andre** [le-andre/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can play a game based off of an existing game, called Wordle.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can either type, or click on the virtual keyboard to input letters to guess a word.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103016667/181086589-37813fe8-4a2b-4f18-b46f-cdacdaf5381b.png)
![image](https://user-images.githubusercontent.com/103016667/181086367-a8044c68-a85b-4991-9b46-fe8cb4e79f42.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
### ⚡ Client Tasks

- [x] Create how to play modal
- [x] Create a word guessing game inspired by hangman
- [x] Create rules for the guessing game
  - [x] Win condition added
  - [x] Lose condition added
- [x] Create a component to display a virtual keyboard
  - [x] Allow for user to click on virtual keyboard to input letters
- [x] Create a component for the NAV bar
  - [x] Home page
  - [x] Leadboard page
  - [x] How to play page
  - [x] Chatroom page
  
### ⚡Stretch features

- [ ] Display a hangman model that changes according to how many attempts
  - [ ] Add a maximum amount of attempts
### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [ ] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
